from shapes import cuboid,sphere ,rectangle ,circle

r=int(input("Enter the radius of circle:")) 
circle.CircleArea(r) 
circle.CirclePerimeter(r) 
l=int(input("Enter the length of rectangle:")) 
b=int(input("Enter the breadth of rectangle:")) 
rectangle.RectArea(l,b) 
rectangle.RectPerimeter(l,b) 
l1=int(input("Enter the length of cuboid:")) 
b1=int(input("Enter the breadth of cuboid:")) 
h1=int(input("Enter the height of cuboid:")) 
cuboid.CuboidArea(l1,b1,h1) 
cuboid.CuboidPerimeter(l1,b1,h1) 
r1=int(input("Enter the radius of sphere:")) 
sphere.SphereArea(r1) 
sphere.SpherePerimeter(r1) 
